### ISSUE TITLE
ability to use ctx.load for UserData methods

### ISSUE THREAD

**Issue by marius851000** [mlua-rs/rlua#166]
In the program I’m working on, I use yield to implement cooperative multitasking. There are locking function, that use coroutine.yield to return some data. As said here ( https://github.com/kyren/rlua/issues/121 ), I can’t yield from a rust function, so I use ctx.load(…) to load a lua function that call the rust function, then yield the returned value. The problem is that I can’t do that with the UserDataMethods object for UserData, and I can’t change the lua-side API. So I ask the ability to use something similar, that will allow to load a lua function with UserDataMethods (or an alternative that will allow to yield from a UserDataMethods). Also, I don't have enought programming competence with lua and rust FFI to implement this.

**Comment by kyren** [comment]
I'm not sure I understand what you're asking for.

If you can do something with a normal Lua callback you can do it with a UserData method, though depending on what you're doing you may have to use `UserDataMethods::add_function` or similar and accept an `AnyUserData` as the first argument.  It should be exactly the same then as if you had made a free function.

**Comment by marius851000** [comment]
Sorry for not being clear enougth.

basically, every `UserDataMethods` accepts either `Fn` or `FnMut`. Those they needs to be rust function, and so, they can't call `coroutine.yield`. I have in a file

```rust
use crate::gamedata::{Scene, Update, Lock, Time};
use rlua::{UserData, UserDataMethods};
use std::sync::{Arc, Mutex, atomic::AtomicBool};
use crate::YieldResult;
use crate::LockReason;
use rlua::Function;

pub struct TASK {
    scene: Arc<Mutex<Scene>>,
}

impl TASK {
    pub fn new(scene: Arc<Mutex<Scene>>) -> Self {
        Self { scene }
    }
}

impl UserData for TASK {
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method("_Sleep", |ctx, this, time: Time| {
            println!("ok");
            let mut scene = this.scene.lock().unwrap();
            let abool = Arc::new(AtomicBool::new(false));
            scene.update(Update::AddLock(Lock::Wait(abool.clone(), time)));
            Ok(YieldResult::new(LockReason::new_abool(abool)))
        });
    }
}
```

I then want to be able to call `TASK:Sleep(time)`. This need to be a native lua function, as they need to yield. So I would like to be able to do something like:
```rust
impl UserData for TASK {
    fn add_methods<'lua, M: UserDataMethods<'lua, Self>>(methods: &mut M) {
        methods.add_method("_Sleep", |ctx, this, time: Time| {
            println!("ok");
            let mut scene = this.scene.lock().unwrap();
            let abool = Arc::new(AtomicBool::new(false));
            scene.update(Update::AddLock(Lock::Wait(abool.clone(), time)));
            Ok(YieldResult::new(LockReason::new_abool(abool)))
        });

        methods.add_method_load("Sleep", "function Sleep(this, time)
            coroutine.yield(this._Sleep(time))
        end");
    }
}
```

I am able to do this with for globals function(in another file)

```rust
pub fn add_locking_function<'lua>(
    ctx: &Context<'lua>,
    front_user_function_name: &str,
    internal_function_name: &str,
    internal_function: Function<'lua>,
) {
    let globals = ctx.globals();
    globals
        .set(internal_function_name, internal_function)
        .unwrap();
    let front_function = ctx
        .load(&format!("local temp_result = {}()\ncoroutine.yield(temp_result)", internal_function_name))
        .into_function()
        .unwrap();
    globals
        .set(front_user_function_name, front_function)
        .unwrap();
}
```

And it work. Would like to be able to do something like that for a `UserData` methods

**Comment by kyren** [comment]
This is unrelated, but you don't have to use a global function to wrap your callback in order to yield in your global example, you could use something like `Function::bind` to not have to pollute the global scope.

I do understand now why it is difficult to yield from a UserData method, you can't wrap the method in a Lua function to do the yield for you.  The only thing you could do is wrap the entire datatype in your own table with its own metamethods which forward to the userdata methods, and I understand that that may be inconvenient.

As a quick fix, I *think* it might be possible to safely add the ability to add arbitrary `Function` types to the userdata metatable, allowing you to have a pure-lua userdata method.  I think that's useful for more than just this, though it is pretty niche.  I'd be happy to mentor making this PR, otherwise I'm not sure when I could get around to it.

Longer term, there should be a way to yield from a rust callback or even arbitrary generator integration, but I don't have a lot of time to devote to designing such an API right now.

**Comment by marius851000** [comment]
Ok. I will try to work on this.

**Comment by marius851000** [comment]
I've took a look at the code, and I've actually two question.

First, the UserDataMethods is a trait. I have no problem from a lifetime POV to transfert Lua to StaticUserDataMethods, but there is lifetimes conflict in NonStaticUserData. I'm not sure of how to solve this. In my program, I only use StaticUserDataMethods.

The second question is how should I expose the API. I could use something like
```lua
coroutine.yield(_rust_function(argument1))
```
called with
```
methods.try_function_lua("lua_function", the_lua_code).unwrap();
```
but then there need to be a way to define the name of arguments. (argument1 is not named in function call.

On an other side, I could use
```lua
function lua_function(argument1)
    coroutine.yield(_rust_function(argument1))
end
```
called with
```rust
methods.try_function_lua("lua_function", the_lua_code).unwrap();
```
That second way should be easier to use, and maybe it is the best one, but it doesn't seem very good way to integrate this (but that shouldn't be too much of a problem). I hope you can answer my question.

**Comment by marius851000** [comment]
I figured that what I previously wrote was wrong about the API, and, based on the example of ``Function::call``, the api could be something like the first approach, with:
```lua
function(self, time_to_sleep)
    coroutine.yield(self._sleep_internal(time_to_sleep))
end
```
and
```rust
methods.try_function_lua("sleep", the_lua_code).unwrap()
```
This should work on StaticUserDataMethods and unwrap with NonStaticUserDataMethods. I will try to implement this later today. (
I could implement it with something like:
```rust
Function = lua_context.load(lua_function).into_function()?;
self.methods_function.push(compiled_func);
```

and something similar for meta methods.

**Comment by marius851000** [comment]
I'm now having a new problem: I was able to implement the api defined before ( ``methods.try_function_lua("sleep", the_lua_code).unwrap()`` ) and call function with it. However, the self value is stored on the stack, and I can't find how to get it without running rust code. Do you have an hint to help me ?

**Comment by marius851000** [comment]
I found that a potential tempory solution would be to have a get_self function, that return the latest userdata in the stack. It however doesn't seem very good from a lua api perspective.

**Comment by marius851000** [comment]
It's too hard. I'll probably stop this, and just make some patch to the lua code, that it replace
```lua
stuff.call_method(1, 2)
```
to
```lua
stuff.call_method(stuff, 1, 2)
```

**Comment by jugglerchris** [comment]
If the Lua code is calling `stuff.call_method(1, 2)` then you're right, `stuff` isn't passed to the method - a method call in Lua is `stuff:call_method(1, 2)` which is equivalent to `stuff.call_method(stuff, 1, 2)`.
To make the first one work you would need to make `call_method` be a closure which captures `stuff`.  I think this could be done by implementing the `__index` metamethod.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon in favour of mlua, which support yielding in functions/methods in async context.
If any further functionality required please open a new issue in the mlua repo.
