### ISSUE TITLE
Document the units of `set_memory_limit` and `used_memory`

### ISSUE THREAD

**Issue by mkhan45** [mlua-rs/rlua#181]
Right now the documentation for `Lua::used_memory` and `Lua::set_memory_limit` doesn't specify the unit. This could be a doc fix, but IMO it would be better to rename the functions like `Lua::used_memory_kbytes` etc.

**Comment by lol218** [comment]
Did the project die since this request was made?

**Comment by mkhan45** [comment]
Yeah, the standard is now mlua: https://github.com/khvzak/mlua

**Comment by lol218** [comment]
Thanks, a lot.

**Comment by jugglerchris** [comment]
I wouldn't exactly say that rlua is dead - there are new releases now and then.  mlua is evidently more active, though.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon and this issue is solved in mlua.
