### ISSUE TITLE
rlua::Lua needs compile time option for Send or not Send

### ISSUE THREAD

**Issue by jugglerchris** [mlua-rs/rlua#188]
As copied from https://github.com/amethyst/rlua/issues/172#issuecomment-616975763 

`rlua::Lua` needs a compile-time switch to either require `Send` or to not require `Send`. Not-requiring `Send` seems like the obvious choice, but it makes it very hard to integrate into game engines that use threaded systems or perhaps into things like web servers.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon in favour of mlua, where is feature is already supported (via `send` feature flag).
