### ISSUE TITLE
rlua needs to either not use the lua_State "extradata" region or have a way to turn it off

### ISSUE THREAD

**Issue by jugglerchris** [mlua-rs/rlua#189]
As copied from https://github.com/amethyst/rlua/issues/172#issuecomment-616975763 

`rlua` needs to either not use the `lua_State` "extradata" region or have a way to turn it off so it doesn't conflict with things trying to use it to create stand-alone Lua modules. The "extradata" region is unfortunately the fastest way to store arbitrary data alongside the main Lua state, which is why this has not been addressed yet.

**Comment by khvzak** [comment]
rlua going to be deprecated soon and this issue is already solved in mlua
