### ISSUE TITLE
consider expose ffi mod or create rlua-sys crate

### ISSUE THREAD

**Issue by clouds56** [mlua-rs/rlua#197]
I'd like to use lua_getupvalue, lua_setupvalue and lua_pushcclosure to create a closure (other than function which has 0 upvalue), is it possible to use ffi directly outside the crate?

**Comment by jugglerchris** [comment]
Hi,
I don't think we'd want to expose `ffi` directly as it's too easy to break rlua's invariants.
It may make sense adding a way to create a closure with upvalues (a variant of [`Context::create_function()`](https://docs.rs/rlua/0.17.0/rlua/struct.Context.html#method.create_function)).
However, does [`Function::bind()`](https://docs.rs/rlua/0.17.0/rlua/struct.Function.html#method.bind) give you the functionality you need?

**Comment by clouds56** [comment]
Yes, I'm using bind for now, but it seems using a different way to do this and I worried about performance since it always create a new function when bind and call.
I think it make sense to have API like
```rust
Context::create_closure(Fn(LuaContext, /* upvalue */ FromLuaMulti, /* args */ FromMulti) -> ToMultiValue) -> LuaClosure
Closure::with_upvalues(values: FromLuaMulti) -> LuaFunction
```

**Comment by jugglerchris** [comment]
I've added the Future label as I think this needs a bit of investigation to see whether it does make a difference to performance or convenience, and can be added later.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon and this feature is already supported by mlua, see [mlua-sys](https://crates.io/crates/mlua-sys) crate which is available directly from mlua as `mlua::ffi`
