### ISSUE TITLE
Allow unsafe direct access to Lua state

### ISSUE THREAD

**Issue by jugglerchris** [mlua-rs/rlua#209]
We should:
* Add a way to get an `ffi::lua_State` pointer from an existing `Lua`.
* Add a way to construct a `Lua` from an externally created `ffi::lua_State`

Both should be `unsafe` in the Rust sense.

As part of this we also need to:
* Document what is safe or not
* Stop using the Lua "extra data" (from `lua_getextraspace()`)

See #137 for some discussion.

**Comment by khvzak** [comment]
This feature is supported by mlua, see [`Lua::create_c_function`](https://docs.rs/mlua/latest/mlua/struct.Lua.html#method.create_c_function) to get access to raw `lua_State`. [`mlua-sys`](https://crates.io/crates/mlua-sys) can be used to utilize raw C api in mlua.
