### ISSUE TITLE
[Typo] Example says laoded(instead of loaded)

### ISSUE THREAD

**Issue by Ciel-MC** [mlua-rs/rlua#296]
https://github.com/mlua-rs/rlua/blob/e47db6abd33ea5fbb2242db238484aeba90c0e72/examples/guided_tour.rs#L46

Sorry

**Comment by khvzak** [comment]
Thank you.
rlua currently under the process of merging with mlua, so I [fixed](https://github.com/mlua-rs/mlua/commit/804972b0992755b0f532f6b1032e44b9602fdfea) some typos there.
